apiVersion: v1
kind: Pod
metadata:
  name: kuard-pod
spec:
  containers:
    - name: kuard-pod
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      command:
        - '/kuard'
        - '$(EXTRA-PARAM)'
      # Env variable from config map 
      #env:
      #- name: ANOTHER-PARAM
      #  valueFrom:
      #    configMapKeyRef:
      #      name: another-param
      #      key: another-param
      # Env variable from another variable
      env:
        - name: EXTRA-PARAM
          valueFrom:
            configMapKeyRef:
              name: postgres-cm 
              key: extra-param 

        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-cm
              key: POSTGRES_USER 

  restartPolicy: Never
