apiVersion: v1
kind: Pod
metadata:
  name: my-kuard
spec:
  containers:
    - name: my-kuard
      image: gcr.io/kuar-demo/kuard-amd64:blue
      imagePullPolicy: Always
      command:
        - "/kuard"
        - --"$(ADDRESS)"
      env:
        # An example of an environmental variable used inside the container
        - name: ANOTHER_PARAM
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: another-parameter
        
        # An example of environment variable passed to the command to start the container
        - name: ADDRESS 
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: address 
      volumeMounts:
        # Mounting the configMap as a set of files
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: my-config
  restartPolicy: Never
